
namespace Common.Win32.Com.Property
{
    public enum EVarType : ushort
    {
        Empty = 0,
        Null = 1,
        I2 = 2,
        I4 = 3,
        R4 = 4,
        R8 = 5,
        Cy = 6,
        Date = 7,
        Bstr = 8,
        Dispatch = 9,
        Error = 10,
        Bool = 11,
        Variant = 12,
        Unknown = 13,
        Decimal = 14,
        I1 = 16,
        Ui1 = 17,
        Ui2 = 18,
        Ui4 = 19,
        I8 = 20,
        Ui8 = 21,
        Int = 22,
        Uint = 23,
        Void = 24,
        Hresult = 25,
        Ptr = 26,
        Safearray = 27,
        Carray = 28,
        Userdefined = 29,
        Lpstr = 30,
        Lpwstr = 31,
        Record = 36,
        IntPtr = 37,
        UintPtr = 38,
        Filetime = 64,
        Blob = 65,
        Stream = 66,
        Storage = 67,
        StreamedObject = 68,
        StoredObject = 69,
        BlobObject = 70,
        Cf = 71,
        Clsid = 72,
        VersionedStream = 73,
        BstrBlob = 0xfff,
        Vector = 0x1000,
        Array = 0x2000,
        Byref = 0x4000,
        Reserved = 0x8000,
    }
}
